name: Android build on feature

on:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
    branches:
      - '**'
      - '!main'

jobs:
  test:
    name: Test source code
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Load Gradle from cache
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Run tests
        run: ./gradlew testDebugUnitTest --continue
      - name: Upload reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path:
            ./app/build/reports/tests/**
  lint:
    name: Lint source code
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Load Gradle from cache
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Run linting
        run: ./gradlew lintDebug
      - name: Upload reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: lint-reports
          path:
            ./app/build/reports/lint*